#
# JWT properties
#
jwt:
  salt: testSalt

jwks:
  uri: http://localhost:9090/oauth2/jwks


server:
  port : 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hr
    username: root
    password: '[D5DQYn}+goNs&x7R&d!/kJbE!xr^E'
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090
